# Generated by Django 4.0.5 on 2022-06-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seasons_seasons_alter_series_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.year', verbose_name='Года'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='year',
            name='years',
            field=models.CharField(max_length=4, verbose_name='Года'),
        ),
    ]
